
userName = input("what is you user name ?:")
x = input("quel est ta ton aliment préféré?:")
y = input("quel est ta musique préférée?:")
u = input("ou vis tu?:")
print()
print("Bienvenu") 
print(userName)
print ("tu aime manger")
print (x)
print ("et tu adore")
print (y)
print (" et tu vis a")
print (u)
print ("cest super!")